language: php
php:
  - '5.5'

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
 - openssl aes-256-cbc -K $encrypted_bc89d497c4ec_key -iv $encrypted_bc89d497c4ec_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
 - tar -xzf credentials.tar.gz
 - cp .env.example .env

install:
 - composer install --no-dev --no-interaction --optimize-autoloader

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: Zync-a37245d0309a.json
  project: zync-b3bce
  default: true
  on: release

notifications:
  slack:
    secure: HajCCmf1l4b40wxrgUc2GZQP6ORbCXv8dfwtR0plcJU2DNfQTkCztbisPeflocVPt+WwhMReEEd/CvNjT2qyypprUnF3M5dagoBbDIqKzPuIC+jwtKVlSh5K7sIs435KFIhP65XjdM8N10x6DUMvUfxlEIjdislCdOAbbeVan00OZvAcVDKk0cB47gL1Lk1XYgwLvaRHyEauykZB31uvo0SVA3b9LC4ZsrgPy0yd/n0qizZlGJoCIcWjQb0rHYtFEPv9iaOft4z+QEIieL60KVccce/xSEKfL317uemPPVv/XVnG8ZKAVpy+E2Y9T1pHSZhDTGXVdtVMMKYHJ1Osw+LCtFvVYeudE6gQScJuIce/jm5nKj2A2RrtH81ORIqUobjtSI2Gr5ZNyS9i1KXpIOPMmfy81DLr+CwhovFgHO61Nq1B381GzWvXLk4BeHbbSWXKQtq4Exf7jmHmYLfOBbNr7IKwmDXYqWtNIAwEUE56UEb9hs8qgUBHm5T4oZvhlSCREPT9Yt74pv03XXaPiC9YDBEgSiRkFlPYufxYw3QhU6nFp7TFtnsar/FEoG0+i3tBFnnilHJOIfxQePanTvhvBkFV9dzWAcpQxbOMoQN8fWq7i6MVfd0Vada+XTrBNGETBHpXFsLKWe8kwKRSB9vj1Aiu63+d+6uGm34DCm0=