language: php
php:
  - '5.5'

before_install:
 - openssl aes-256-cbc -K $encrypted_bc89d497c4ec_key -iv $encrypted_bc89d497c4ec_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
 - tar -xzf credentials.tar.gz
 - cp .env.example .env

install:
 - composer install --no-dev --no-interaction --optimize-autoloader

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: Zync-a37245d0309a.json
  project: zync-b3bce
  default: true
  on: master
