runtime: php55
api_version: 1

handlers:
- url: /.well-known
  static_dir: .well-known

- url: /.*
  script: public/index.php

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\.git$
- ^(.*/)?composer.phar$
- ^(.*/)?phpunit.xml$
- ^(.*/)?/tests$
- ^.env.example$
- ^tests$
- ^storage$
- ^artisan$
- ^.idea$
