runtime: php55
api_version: 1

handlers:
- url: /.well-known
  static_dir: .well-known

- url: /.*
  script: public/index.php

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\.git.*$
- ^(.*)?/tests/.*$
- ^tests$
- ^storage$
- ^(.*)?composer.phar$
- ^\.env\.example$
- ^artisan$
- ^(.*)?phpunit.xml$
- ^.idea$
